#[app]
#save_dir = C:/Users/Lab/Documents/MicroscopeData

[hardware/prior_stage]
port = 3
speed_xy = 5.0

[hardware/prior_purefocus]
port = 4

[hardware/prior_turret]
sync_purefocus = True

#[hardware/zwo_camera]
#cam_id = 0

#[measurement/prior_stage_control]
#jog_step_xy = 0.1

[measurement/simple_tiled_image]
h0 = -10.0
h1 = 10.0
v0 = -10.0
v1 = 10.0
Nh = 10
Nv = 10
