apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mosaic-stitch-consumer
  name: mosaic-stitch-consumer
  namespace: default
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mosaic-stitch-consumer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mosaic-stitch-consumer
      name: mosaic-stitch-consumer
      namespace: default
    spec:
      containers:
      - env:
        - name: PYTHONUNBUFFERED
          value: "true"
        - name: CRUCIBLE_API_URL
          value: "https://crucible.lbl.gov/api/v2"
        - name: RMQ_HOST
          value: '10.128.0.31'
        - name: RMQ_PORT
          value: '5672'
        - name: SECRET_STORE
          value: "projects/776258882599/secrets"
        image: us-central1-docker.pkg.dev/mf-crucible/mosaic-stitch-consumer/main:latest
        imagePullPolicy: Always
        name: mosaic-stitch-consumer
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
            ephemeral-storage: 8Gi
          requests:
            cpu: 2000m
            memory: 4Gi
            ephemeral-storage: 8Gi
        securityContext:
          capabilities:
            drop:
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/arch
        operator: Equal
        value: amd64